import { validateOpenAIKey } from "./src/lib/openai-key-validation";

// @ts-expect-error — generated by opennextjs-cloudflare build
import { default as handler } from "./.open-next/worker.js";

type ValidationBody = {
  apiKey: string;
};

/** Validates OpenAI keys from wnam (US) so blocked edge colos (e.g. HKG) do not call OpenAI directly. */
export class OpenAIValidationDO {
  async fetch(request: Request): Promise<Response> {
    if (request.method !== "POST") {
      return Response.json({ ok: false, message: "Method not allowed" }, { status: 405 });
    }

    let body: ValidationBody;
    try {
      body = (await request.json()) as ValidationBody;
    } catch {
      return Response.json({ ok: false, message: "Invalid JSON body" }, { status: 400 });
    }

    const result = await validateOpenAIKey(body.apiKey ?? "");
    return Response.json(result, { status: result.ok ? 200 : 400 });
  }
}

export default handler;
