import { createOpenAI } from "@ai-sdk/openai";
import { generateText } from "ai";

// @ts-expect-error — generated by opennextjs-cloudflare build
import { default as handler } from "./.open-next/worker.js";

const OPENAI_VALIDATION_URL = "https://api.openai.com/v1";
const OPENAI_TEST_MODEL = "gpt-4o-mini";
const OPENAI_TEST_PROMPT = "hello";

type ValidationBody = {
  apiKey: string;
  model?: string;
};

async function runOpenAIKeyValidation(body: ValidationBody) {
  const apiKey = body.apiKey?.trim();
  if (!apiKey) {
    return { ok: false as const, message: "`apiKey` is required." };
  }

  try {
    const openai = createOpenAI({
      apiKey,
      baseURL: OPENAI_VALIDATION_URL,
    });

    await generateText({
      model: openai.chat(body.model ?? OPENAI_TEST_MODEL),
      prompt: OPENAI_TEST_PROMPT,
    });

    return { ok: true as const, message: "OpenAI key is valid." };
  } catch (error) {
    const details =
      error instanceof Error ? error.message : "OpenAI validation failed.";
    return {
      ok: false as const,
      message: "OpenAI key is invalid.",
      details,
    };
  }
}

/** Validates OpenAI keys from wnam (US) so blocked edge colos (e.g. HKG) do not call OpenAI directly. */
export class OpenAIValidationDO {
  async fetch(request: Request): Promise<Response> {
    if (request.method !== "POST") {
      return Response.json({ ok: false, message: "Method not allowed" }, { status: 405 });
    }

    let body: ValidationBody;
    try {
      body = (await request.json()) as ValidationBody;
    } catch {
      return Response.json({ ok: false, message: "Invalid JSON body" }, { status: 400 });
    }

    const result = await runOpenAIKeyValidation(body);
    return Response.json(result, { status: result.ok ? 200 : 400 });
  }
}

export default handler;
