"use client";

import { FormEvent, useState } from "react";
import Image from "next/image";
import type { AIProviderName } from "@/lib/ai-provider";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Text } from "@/components/ui/text";

type MediaLabProps = {
  selectedProvider: AIProviderName;
  openaiApiKey?: string;
  isOpenAIKeyVerified: boolean;
};

type ImageGenerationResponse = {
  mediaType?: string;
  base64?: string;
  error?: string;
};

export function MediaLab({
  selectedProvider,
  openaiApiKey,
  isOpenAIKeyVerified,
}: MediaLabProps) {
  const [imagePrompt, setImagePrompt] = useState("");
  const [imageUrl, setImageUrl] = useState<string | null>(null);
  const [imageError, setImageError] = useState<string | null>(null);
  const [isGeneratingImage, setIsGeneratingImage] = useState(false);

  const isOllamaSelected = selectedProvider === "ollama";
  const trimmedImagePrompt = imagePrompt.trim();
  const isGenerateDisabled =
    isGeneratingImage ||
    isOllamaSelected ||
    !isOpenAIKeyVerified ||
    trimmedImagePrompt.length === 0;

  async function handleGenerateImage(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();

    const prompt = trimmedImagePrompt;
    if (!prompt) return;

    setIsGeneratingImage(true);
    setImageError(null);

    try {
      const response = await fetch("/api/media/image", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          prompt,
          provider: selectedProvider,
          openaiApiKey,
        }),
      });

      const data = (await response.json()) as ImageGenerationResponse;

      if (!response.ok || !data.base64 || !data.mediaType) {
        throw new Error(data.error ?? "Image generation failed.");
      }

      setImageUrl(`data:${data.mediaType};base64,${data.base64}`);
    } catch (error) {
      setImageUrl(null);
      setImageError(error instanceof Error ? error.message : "Unknown error");
    } finally {
      setIsGeneratingImage(false);
    }
  }

  return (
    <section className="space-y-4 rounded-xl border border-slate-200 bg-white p-4 shadow-sm">
      <div>
        <Text as="h2" variant="body" className="font-semibold">
          AI SDK Core Image Lab
        </Text>
        <Text variant="caption">
          This section currently keeps only generateImage.
        </Text>
      </div>

      <div className="rounded-lg border border-slate-200 bg-slate-50 p-3">
        <Text variant="caption">
          Current provider: <strong>{selectedProvider}</strong>
        </Text>
        {isOllamaSelected ? (
          <Text variant="warning" className="mt-1">
            Ollama mode does not expose OpenAI image generation endpoint in this
            project, so image generation is not supported.
          </Text>
        ) : !isOpenAIKeyVerified ? (
          <Text variant="warning" className="mt-1">
            Verify OpenAI key before generating images.
          </Text>
        ) : (
          <Text variant="caption" className="mt-1">
            OpenAI mode is supported for image generation.
          </Text>
        )}
      </div>

      <form onSubmit={handleGenerateImage} className="space-y-2 border-t pt-3">
        <Text variant="body" className="font-medium">
          Image Generation
        </Text>
        <div className="flex gap-2">
          <Input
            value={imagePrompt}
            onChange={(event) => setImagePrompt(event.target.value)}
            fullWidth
            controlSize="md"
            placeholder={
              !isOpenAIKeyVerified
                ? "Verify key first to enter prompt"
                : "Describe the image"
            }
            disabled={!isOpenAIKeyVerified || isOllamaSelected}
            className="flex-1"
          />
          <Button
            type="submit"
            isLoading={isGeneratingImage}
            size="md"
            disabled={isGenerateDisabled}
          >
            {isOllamaSelected
              ? "OpenAI only"
              : !isOpenAIKeyVerified
                ? "Verify key first"
                : isGeneratingImage
                  ? "Generating..."
                  : "Generate"}
          </Button>
        </div>
        {imageError ? <Text variant="error">{imageError}</Text> : null}
        {imageUrl ? (
          <Image
            src={imageUrl}
            alt="Generated by AI SDK"
            width={1024}
            height={1024}
            unoptimized
            className="max-h-72 w-full rounded-lg border border-slate-200 object-contain"
          />
        ) : null}
      </form>
    </section>
  );
}
